journal_articles: []
microlensing_reviews: []
roman_mission:
- description: Spergel et al. (2015) - Wide-Field InfrarRed Survey Telescope-Astrophysics
    Focused Telescope Assets WFIRST-AFTA 2015 Report
  name: Spergel_2015_arXiv_1503.03757
  url: https://arxiv.org/pdf/1503.03757.pdf
